complete -c rp++ -l help -d 'print version information and exit'
complete -c rp++ -l version -d 'print version information and exit'
complete -c rp++ -l file -d 'give binary path'
complete -c rp++ -l info -d 'display information about the binary header'
complete -c rp++ -l rop -d 'find useful gadget for your future exploits, arg is the gadget maximum size in instructions'
complete -c rp++ -l raw -d 'find gadgets in a raw file, \'archi\' must be in the following list: x86, x64' -a 'x86 x64'
complete -c rp++ -l atsyntax -d 'enable the at&t syntax'
complete -c rp++ -l unique -d 'display only unique gadget'
complete -c rp++ -l search-hexa -d 'try to find hex values'
complete -c rp++ -l search-int -d 'try to find a pointer on a specific integer value'
